# Generated by Django 5.2 on 2025-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cartcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
