import type { Metadata } from "next";
import "./globals.css"
import Navbar from "@/components/Navbar";
import { Slider } from "@/components/ui/carousel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <Slider/>
      <body>
        {children}
      </body>
      {/* <footer>i am a footer</footer> */}
    </html>
  );
}
