# Generated by Django 5.2 on 2025-04-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='carid',
            new_name='cardid',
        ),
    ]
