# Generated by Django 5.2 on 2025-04-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_carid_cartmodel_cardid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='cardid',
            new_name='cartid',
        ),
    ]
