# Generated by Django 5.2 on 2025-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_cardid_cartmodel_cartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='cartcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
