# Generated by Django 5.2 on 2025-05-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartmodel_cartcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cartcount',
        ),
    ]
