# Generated by Django 5.2 on 2025-04-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinquirymodel',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customerinquirymodel',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='customerinquirymodel',
            old_name='inquiry',
            new_name='message',
        ),
    ]
